// <auto-generated />
using System;
using BE_MusicStreaming;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BE_MusicStreaming.Migrations
{
    [DbContext(typeof(BE_MusicStreamingDbContext))]
    [Migration("20240424013204_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BE_MusicStreaming.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "OutKast"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beyoncé"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Eminem"
                        },
                        new
                        {
                            Id = 4,
                            Name = "The Killers"
                        },
                        new
                        {
                            Id = 5,
                            Name = "U2"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Coldplay"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shakira"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rihanna"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Snow Patrol"
                        },
                        new
                        {
                            Id = 10,
                            Name = "The Black Eyed Peas"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gnarls Barkley"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Jay-Z"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Amy Winehouse"
                        },
                        new
                        {
                            Id = 14,
                            Name = "System of a Down"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Green Day"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Leona Lewis"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Katy Perry"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Evanescence"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Gwen Stefani"
                        },
                        new
                        {
                            Id = 20,
                            Name = "The White Stripes"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Alicia Keys"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Kanye West"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Taylor Swift"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Justin Timberlake"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Linkin Park"
                        },
                        new
                        {
                            Id = 26,
                            Name = "M.I.A."
                        },
                        new
                        {
                            Id = 27,
                            Name = "Lady Gaga"
                        },
                        new
                        {
                            Id = 28,
                            Name = "R. Kelly"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Avril Lavigne"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Britney Spears"
                        },
                        new
                        {
                            Id = 31,
                            Name = "50 Cent"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Lil Jon & The East Side Boyz"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Usher"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Fergie"
                        });
                });

            modelBuilder.Entity("BE_MusicStreaming.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hip Hop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 4,
                            Name = "R&B"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dance"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Nu Metal"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Alternative Rock"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pop Punk"
                        });
                });

            modelBuilder.Entity("BE_MusicStreaming.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = " https://townsquare.media/site/443/files/2013/06/vid1.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
                            IsFavorite = false,
                            Name = "Y2K Alt Anthems",
                            Public = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/81gEr9Kx1LL._AC_SL1417_.jpg",
                            IsFavorite = true,
                            Name = "Pop Princesses",
                            Public = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i2-prod.mirror.co.uk/incoming/article20126256.ece/ALTERNATES/s615b/0_Britney-Spears-07.jpg",
                            IsFavorite = true,
                            Name = "Love & Heartbreak",
                            Public = false,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BE_MusicStreaming.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Duration = "3:55",
                            GenreId = 2,
                            Name = "Hey Ya!",
                            Year = 2003
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            Duration = "3:56",
                            GenreId = 4,
                            Name = "Crazy In Love",
                            Year = 2003
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            Duration = "6:44",
                            GenreId = 2,
                            Name = "Stan",
                            Year = 2000
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 4,
                            Duration = "3:42",
                            GenreId = 8,
                            Name = "Mr. Brightside",
                            Year = 2003
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 5,
                            Duration = "4:08",
                            GenreId = 3,
                            Name = "Beautiful Day",
                            Year = 2000
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 6,
                            Duration = "5:07",
                            GenreId = 3,
                            Name = "Clocks",
                            Year = 2002
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 7,
                            Duration = "3:39",
                            GenreId = 1,
                            Name = "Hips Don't Lie",
                            Year = 2006
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 6,
                            Duration = "4:01",
                            GenreId = 3,
                            Name = "Viva La Vida",
                            Year = 2008
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 8,
                            Duration = "4:35",
                            GenreId = 4,
                            Name = "Umbrella",
                            Year = 2007
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 3,
                            Duration = "5:20",
                            GenreId = 2,
                            Name = "Lose Yourself",
                            Year = 2002
                        },
                        new
                        {
                            Id = 11,
                            ArtistId = 9,
                            Duration = "4:28",
                            GenreId = 3,
                            Name = "Chasing Cars",
                            Year = 2006
                        },
                        new
                        {
                            Id = 12,
                            ArtistId = 10,
                            Duration = "4:49",
                            GenreId = 1,
                            Name = "I Gotta Feeling",
                            Year = 2009
                        },
                        new
                        {
                            Id = 13,
                            ArtistId = 11,
                            Duration = "2:58",
                            GenreId = 6,
                            Name = "Crazy",
                            Year = 2006
                        },
                        new
                        {
                            Id = 14,
                            ArtistId = 12,
                            Duration = "4:36",
                            GenreId = 2,
                            Name = "Empire State of Mind",
                            Year = 2009
                        },
                        new
                        {
                            Id = 15,
                            ArtistId = 13,
                            Duration = "3:35",
                            GenreId = 6,
                            Name = "Rehab",
                            Year = 2006
                        },
                        new
                        {
                            Id = 16,
                            ArtistId = 14,
                            Duration = "3:30",
                            GenreId = 7,
                            Name = "Chop Suey!",
                            Year = 2001
                        },
                        new
                        {
                            Id = 17,
                            ArtistId = 15,
                            Duration = "4:20",
                            GenreId = 10,
                            Name = "Boulevard of Broken Dreams",
                            Year = 2004
                        },
                        new
                        {
                            Id = 18,
                            ArtistId = 16,
                            Duration = "4:23",
                            GenreId = 1,
                            Name = "Bleeding Love",
                            Year = 2007
                        },
                        new
                        {
                            Id = 19,
                            ArtistId = 2,
                            Duration = "3:13",
                            GenreId = 4,
                            Name = "Single Ladies (Put a Ring on It)",
                            Year = 2008
                        },
                        new
                        {
                            Id = 20,
                            ArtistId = 1,
                            Duration = "3:55",
                            GenreId = 2,
                            Name = "The Way You Move",
                            Year = 2003
                        },
                        new
                        {
                            Id = 21,
                            ArtistId = 17,
                            Duration = "3:40",
                            GenreId = 1,
                            Name = "Hot N Cold",
                            Year = 2008
                        },
                        new
                        {
                            Id = 22,
                            ArtistId = 17,
                            Duration = "3:00",
                            GenreId = 1,
                            Name = "I Kissed a Girl",
                            Year = 2008
                        },
                        new
                        {
                            Id = 23,
                            ArtistId = 18,
                            Duration = "3:56",
                            GenreId = 7,
                            Name = "Bring Me to Life",
                            Year = 2003
                        },
                        new
                        {
                            Id = 24,
                            ArtistId = 18,
                            Duration = "4:24",
                            GenreId = 8,
                            Name = "My Immortal",
                            Year = 2003
                        },
                        new
                        {
                            Id = 25,
                            ArtistId = 19,
                            Duration = "3:19",
                            GenreId = 1,
                            Name = "Hollaback Girl",
                            Year = 2005
                        },
                        new
                        {
                            Id = 26,
                            ArtistId = 20,
                            Duration = "3:52",
                            GenreId = 8,
                            Name = "Seven Nation Army",
                            Year = 2003
                        },
                        new
                        {
                            Id = 27,
                            ArtistId = 21,
                            Duration = "3:30",
                            GenreId = 4,
                            Name = "Fallin'",
                            Year = 2001
                        },
                        new
                        {
                            Id = 28,
                            ArtistId = 22,
                            Duration = "5:12",
                            GenreId = 2,
                            Name = "Stronger",
                            Year = 2007
                        },
                        new
                        {
                            Id = 29,
                            ArtistId = 23,
                            Duration = "3:55",
                            GenreId = 9,
                            Name = "Love Story",
                            Year = 2008
                        },
                        new
                        {
                            Id = 30,
                            ArtistId = 24,
                            Duration = "4:48",
                            GenreId = 4,
                            Name = "Cry Me a River",
                            Year = 2002
                        },
                        new
                        {
                            Id = 31,
                            ArtistId = 25,
                            Duration = "2:44",
                            GenreId = 7,
                            Name = "Bleed It Out",
                            Year = 2007
                        },
                        new
                        {
                            Id = 32,
                            ArtistId = 26,
                            Duration = "3:25",
                            GenreId = 2,
                            Name = "Paper Planes",
                            Year = 2007
                        },
                        new
                        {
                            Id = 33,
                            ArtistId = 8,
                            Duration = "3:59",
                            GenreId = 5,
                            Name = "Disturbia",
                            Year = 2008
                        },
                        new
                        {
                            Id = 34,
                            ArtistId = 27,
                            Duration = "3:58",
                            GenreId = 5,
                            Name = "Poker Face",
                            Year = 2008
                        },
                        new
                        {
                            Id = 35,
                            ArtistId = 28,
                            Duration = "3:06",
                            GenreId = 4,
                            Name = "Ignition (Remix)",
                            Year = 2002
                        },
                        new
                        {
                            Id = 36,
                            ArtistId = 29,
                            Duration = "4:04",
                            GenreId = 10,
                            Name = "Complicated",
                            Year = 2002
                        },
                        new
                        {
                            Id = 37,
                            ArtistId = 29,
                            Duration = "3:23",
                            GenreId = 10,
                            Name = "Sk8er Boi",
                            Year = 2002
                        },
                        new
                        {
                            Id = 38,
                            ArtistId = 29,
                            Duration = "3:43",
                            GenreId = 10,
                            Name = "I'm with You",
                            Year = 2002
                        },
                        new
                        {
                            Id = 39,
                            ArtistId = 30,
                            Duration = "3:30",
                            GenreId = 1,
                            Name = "Oops!... I Did It Again",
                            Year = 2000
                        },
                        new
                        {
                            Id = 40,
                            ArtistId = 30,
                            Duration = "3:18",
                            GenreId = 5,
                            Name = "Toxic",
                            Year = 2003
                        },
                        new
                        {
                            Id = 41,
                            ArtistId = 30,
                            Duration = "3:23",
                            GenreId = 1,
                            Name = "Stronger",
                            Year = 2000
                        },
                        new
                        {
                            Id = 42,
                            ArtistId = 30,
                            Duration = "4:11",
                            GenreId = 5,
                            Name = "Gimme More",
                            Year = 2007
                        },
                        new
                        {
                            Id = 43,
                            ArtistId = 30,
                            Duration = "3:44",
                            GenreId = 5,
                            Name = "Womanizer",
                            Year = 2008
                        },
                        new
                        {
                            Id = 44,
                            ArtistId = 30,
                            Duration = "3:32",
                            GenreId = 1,
                            Name = "Piece of Me",
                            Year = 2007
                        },
                        new
                        {
                            Id = 45,
                            ArtistId = 30,
                            Duration = "3:12",
                            GenreId = 1,
                            Name = "Circus",
                            Year = 2008
                        },
                        new
                        {
                            Id = 46,
                            ArtistId = 30,
                            Duration = "3:33",
                            GenreId = 1,
                            Name = "3",
                            Year = 2009
                        },
                        new
                        {
                            Id = 47,
                            ArtistId = 31,
                            Duration = "3:13",
                            GenreId = 2,
                            Name = "In da Club",
                            Year = 2003
                        },
                        new
                        {
                            Id = 48,
                            ArtistId = 32,
                            Duration = "5:34",
                            GenreId = 2,
                            Name = "Get Low",
                            Year = 2003
                        },
                        new
                        {
                            Id = 49,
                            ArtistId = 32,
                            Duration = "4:03",
                            GenreId = 2,
                            Name = "Get Crunk",
                            Year = 2003
                        },
                        new
                        {
                            Id = 50,
                            ArtistId = 33,
                            Duration = "4:10",
                            GenreId = 2,
                            Name = "Yeah!",
                            Year = 2004
                        },
                        new
                        {
                            Id = 51,
                            ArtistId = 34,
                            Duration = "3:28",
                            GenreId = 4,
                            Name = "London Bridge",
                            Year = 2006
                        },
                        new
                        {
                            Id = 52,
                            ArtistId = 34,
                            Duration = "4:52",
                            GenreId = 5,
                            Name = "Fergalicious",
                            Year = 2006
                        },
                        new
                        {
                            Id = 53,
                            ArtistId = 10,
                            Duration = "4:33",
                            GenreId = 1,
                            Name = "Where Is the Love?",
                            Year = 2003
                        },
                        new
                        {
                            Id = 54,
                            ArtistId = 10,
                            Duration = "3:37",
                            GenreId = 1,
                            Name = "Let's Get It Started",
                            Year = 2004
                        },
                        new
                        {
                            Id = 55,
                            ArtistId = 10,
                            Duration = "5:27",
                            GenreId = 2,
                            Name = "My Humps",
                            Year = 2005
                        });
                });

            modelBuilder.Entity("BE_MusicStreaming.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "I like groovy beats.",
                            Uid = "-NwC_r-_0kdGvf7zTA09",
                            Username = "Johnny Dough"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "First lady of Juicy Couture.",
                            Uid = "-NwC_t92250bx6_IMTc6",
                            Username = "Janet Smithy"
                        });
                });

            modelBuilder.Entity("PlaylistSong", b =>
                {
                    b.Property<int>("PlaylistsId")
                        .HasColumnType("integer");

                    b.Property<int>("SongsId")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistsId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("PlaylistSong");
                });

            modelBuilder.Entity("BE_MusicStreaming.Models.Playlist", b =>
                {
                    b.HasOne("BE_MusicStreaming.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_MusicStreaming.Models.Song", b =>
                {
                    b.HasOne("BE_MusicStreaming.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_MusicStreaming.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("PlaylistSong", b =>
                {
                    b.HasOne("BE_MusicStreaming.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_MusicStreaming.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
